name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Building
      run: | 
        make
        mkdir release
        cp helloos.img release
        
    - name: Upload release asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{env.strDate}}
        file: release/helloos.img
        file_glob: true
        overwrite: true
        release_name: ${{env.strDate}} 自动发布

