name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Building
      run: | 
        make
        mkdir release
        cp helloos.img release
        
    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{env.strDate}}
        title: ${{env.strDate}} 自动发布
        prerelease: false
        files: |
          release/helloos.img

